/**
 * 
 */
package de.hdm_stuttgart.huber.itprojekt.shared.domainobjects;

import java.sql.Date;

/**
 * @author elcpt
 *
 */
public class NoteBook extends DomainObject {

	/**
	 * #AUTOGENERATED
	 */
	private static final long serialVersionUID = 1L;

	private String title;
	private String subtitle;
	private NoteUser owner;
	private Date creationDate;
	private Date modificationDate;

    public NoteBook() {
    }

    // REINE TESTMETHODE!!!
    public NoteBook(int id) {
        this.id = id;
    }

    public NoteBook(int id, String title, String subtitle, NoteUser owner, Date creationDate, Date modificationDate) {

        this.id = id;
        this.title = title;
        this.subtitle = subtitle;
        this.owner = owner;
        this.creationDate = creationDate;
        this.modificationDate = modificationDate;
    }

    @Override
	public String toString() {
		return "NoteBook{" +
				"title='" + title + '\'' +
				", subtitle='" + subtitle + '\'' +
				", owner=" + owner +
				", creationDate=" + creationDate +
				", modificationDate=" + modificationDate +
				'}';
	}

	public int getId() {
        return this.id;
    }
    public String getTitle() {
        return title;
    }

    public String getSubtitle() {
        return subtitle;
    }

    public NoteUser getOwner() {
        return owner;
    }

    public Date getCreationDate() {
        return creationDate;
    }

    public Date getModificationDate() {
        return modificationDate;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public void setSubtitle(String subtitle) {
        this.subtitle = subtitle;
    }

    public void setOwner(NoteUser owner) {
        this.owner = owner;
    }

    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    public void setModificationDate(Date modificationDate) {
        this.modificationDate = modificationDate;
    }
}
